DROP TABLE IF EXISTS WEAK_ENTITY;
DROP TABLE IF EXISTS TABLE2;
DROP TABLE IF EXISTS TABLE1;

CREATE TABLE TABLE1 (
	T1PK_NO  DECIMAL(11),
	CONSTRAINT PRIMARY KEY(T1PK_NO)
);

CREATE TABLE TABLE2 (
	T2PK_CODE DECIMAL(9),
	CONSTRAINT PRIMARY KEY (T2PK_CODE)
);

CREATE TABLE WEAK_ENTITY (
	T1PK_NO DECIMAL(11)REFERENCES TABLE1(T1PK_NO),
	T2PK_CODE DECIMAL(9)REFERENCES TABLE2(T2PK_CODE),
	CONSTRAINT PRIMARY KEY (T1PK_NO, T2PK_CODE)
);